"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {CalendarDays,ChartNoAxesCombined,ClipboardList,CreditCard,Gift,LayoutDashboard,LogOut,Settings,Store,Users,UsersRound} from "lucide-react";import {getSupabaseBrowser} from "@/lib/supabase";
type Business={id:string;name:string;slug:string;published:boolean};type Service={id:string;name:string;duration_minutes:number;price_cents:number};
const nav=[[LayoutDashboard,"Overview"],[CalendarDays,"Calendar"],[ClipboardList,"Bookings"],[Users,"Customers"],[UsersRound,"Staff"],[Store,"Booking site"],[Gift,"Loyalty"],[ChartNoAxesCombined,"Reports"],[CreditCard,"Payments"],[Settings,"Settings"]];
export default function DashboardApp(){const supabase=getSupabaseBrowser(),router=useRouter();const[business,setBusiness]=useState<Business|null>(null),[services,setServices]=useState<Service[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState("Overview");useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const{data:b}=await supabase.from("businesses").select("id,name,slug,published").eq("owner_id",user.id).limit(1).maybeSingle();if(!b){router.replace("/onboarding");return}setBusiness(b);const{data:s}=await supabase.from("services").select("id,name,duration_minutes,price_cents").eq("business_id",b.id);setServices(s||[]);setLoading(false)})()},[]);async function logout(){await supabase.auth.signOut();router.replace("/")}
if(loading)return <main className="wizard-wrap"><div className="wizard-card"><div className="loader"/><p>Loading your business…</p></div></main>;
return <main className="app-shell"><aside className="app-sidebar"><Link href="/" className="brand"><span className="brand-mark">B</span>Bookd</Link><div className="business-chip"><small>BUSINESS</small><b>{business?.name}</b></div>{nav.map(([Icon,label])=><button onClick={()=>setTab(label as string)} className={tab===label?"app-nav active":"app-nav"} key={label as string}><Icon size={17}/>{label as string}</button>)}<button className="app-nav logout" onClick={logout}><LogOut size={17}/>Log out</button></aside><section className="app-main"><header className="app-header"><div><span>{business?.name}</span><h1>{tab}</h1></div><div className="actions"><Link className="btn btn-secondary" target="_blank" href={`/b/${business?.slug}`}>View booking site</Link><button className="btn btn-primary">+ New booking</button></div></header>{tab==="Overview"?<Overview business={business!} services={services}/>:<ModulePlaceholder title={tab} business={business!}/>}</section></main>}
function Overview({business,services}:{business:Business;services:Service[]}){return <><div className="real-metrics">{[["Bookings","0","No bookings yet"],["Revenue","$0","No payments yet"],["Customers","0","Build your customer list"],["Services",String(services.length),"Active services"]].map(x=><article className="feature" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><div className="dash-columns"><article className="feature empty-panel"><div className="empty-icon"><CalendarDays/></div><h3>Your calendar is ready</h3><p>Bookings will appear here as customers schedule through your site or you add them manually.</p><button className="btn btn-primary">Create first booking</button></article><article className="feature"><h3>Launch checklist</h3>{[[true,"Business created"],[services.length>0,"Add your services"],[business.published,"Publish booking site"],[false,"Set business hours"],[false,"Connect Stripe"]].map(([done,label],i)=><div className="check-row" key={label as string}><span className={done?"done":""}>{done?"✓":i+1}</span>{label as string}</div>)}</article></div></>}
function ModulePlaceholder({title,business}:{title:string;business:Business}){return <article className="feature module-empty"><div className="empty-icon"><span>＋</span></div><h2>{title}</h2><p>This is {business.name}’s {title.toLowerCase()} workspace. It starts empty and will fill with your real business information.</p><button className="btn btn-primary">Set up {title.toLowerCase()}</button></article>}
